// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemService.Domain;

namespace SystemService.Domain.Migrations
{
    [DbContext(typeof(SystemDBContext))]
    [Migration("20191025025629_20191023")]
    partial class _20191023
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CommonLibrary.Recycle", b =>
                {
                    b.Property<string>("TenantCode");

                    b.Property<Guid>("ID");

                    b.Property<DateTimeOffset>("CreateIn");

                    b.Property<string>("CreatedBy");

                    b.Property<Guid>("DeleteBatchID");

                    b.Property<string>("OwnerScopeCode");

                    b.Property<string>("RowData")
                        .IsRequired();

                    b.Property<Guid>("RowKey");

                    b.Property<string>("TableName")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("UpdateIn");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("TenantCode", "ID");

                    b.HasIndex("TenantCode");

                    b.ToTable("Recycle");
                });

            modelBuilder.Entity("SystemService.Domain.Resource", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateIn");

                    b.Property<string>("CreatedBy");

                    b.Property<Guid>("ParentResourceID");

                    b.Property<string>("ResourceCode")
                        .IsRequired();

                    b.Property<string>("ResourceDesc");

                    b.Property<string>("ResourceName")
                        .IsRequired();

                    b.Property<int>("ResourceType");

                    b.Property<int>("SortNO");

                    b.Property<DateTimeOffset?>("UpdateIn");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("ID");

                    b.HasIndex("ParentResourceID");

                    b.HasIndex("ResourceCode")
                        .IsUnique();

                    b.ToTable("Resource");

                    b.HasData(
                        new
                        {
                            ID = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "RootMenu",
                            ResourceName = "RootMenu",
                            ResourceType = 1,
                            SortNO = 0
                        },
                        new
                        {
                            ID = new Guid("5ae86054-b6c8-4408-a0d3-fe3b060c53e9"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "Permission.GetUserMenus",
                            ResourceName = "获取用户菜单",
                            ResourceType = 2,
                            SortNO = 0
                        },
                        new
                        {
                            ID = new Guid("c58858e2-861c-4e06-8917-4d853ac86dfe"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "ProductMngmt",
                            ResourceName = "产品管理",
                            ResourceType = 1,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("c119ac7b-2c52-40dc-93e2-7467623efa4f"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("c58858e2-861c-4e06-8917-4d853ac86dfe"),
                            ResourceCode = "ProductMngmt.Read",
                            ResourceName = "查看",
                            ResourceType = 2,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("0da1e306-9e27-41ea-af0a-4b492f21c45a"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("c58858e2-861c-4e06-8917-4d853ac86dfe"),
                            ResourceCode = "ProductMngmt.Add",
                            ResourceName = "添加",
                            ResourceType = 2,
                            SortNO = 2
                        },
                        new
                        {
                            ID = new Guid("306f47d5-1ae0-4e1f-b192-b0487c8fbbed"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("0da1e306-9e27-41ea-af0a-4b492f21c45a"),
                            ResourceCode = "ProductMngmt.Add.AddBtn",
                            ResourceName = "添加按钮",
                            ResourceType = 3,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("20816b2d-79ff-4731-8cf7-76e0c05e172e"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("c58858e2-861c-4e06-8917-4d853ac86dfe"),
                            ResourceCode = "ProductMngmt.Edit",
                            ResourceName = "修改",
                            ResourceType = 2,
                            SortNO = 3
                        },
                        new
                        {
                            ID = new Guid("2c702c83-c8d4-41f5-a57e-64a770105538"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("c58858e2-861c-4e06-8917-4d853ac86dfe"),
                            ResourceCode = "ProductMngmt.Delete",
                            ResourceName = "删除",
                            ResourceType = 2,
                            SortNO = 4
                        },
                        new
                        {
                            ID = new Guid("3a394bcb-76ef-43fe-8bfc-e56016405c4d"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "OrderingMngmt",
                            ResourceName = "订单管理",
                            ResourceType = 1,
                            SortNO = 2
                        },
                        new
                        {
                            ID = new Guid("9b9c3ebb-f4fc-4347-a03e-5364bbee973d"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "PaymentMngmt",
                            ResourceName = "支付管理",
                            ResourceType = 1,
                            SortNO = 3
                        },
                        new
                        {
                            ID = new Guid("897335d5-562b-4e86-85e0-8aff46d01f7a"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "SystemMngmt",
                            ResourceName = "系统管理",
                            ResourceType = 1,
                            SortNO = 4
                        },
                        new
                        {
                            ID = new Guid("84448bbd-1ada-458d-8c9f-799c07331e51"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("897335d5-562b-4e86-85e0-8aff46d01f7a"),
                            ResourceCode = "SystemMngmt.PermissionMngmt",
                            ResourceName = "权限管理",
                            ResourceType = 1,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("ff494d37-c94c-487b-95bd-863a8bdaddb9"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("84448bbd-1ada-458d-8c9f-799c07331e51"),
                            ResourceCode = "SystemMngmt.PermissionMngmt.RoleMngmt",
                            ResourceName = "角色管理",
                            ResourceType = 1,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("b86aa3c8-0c2e-4f60-ac24-fb76ce513aad"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("ff494d37-c94c-487b-95bd-863a8bdaddb9"),
                            ResourceCode = "SystemMngmt.PermissionMngmt.RoleMngmt.Read",
                            ResourceName = "查看",
                            ResourceType = 2,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("66955fbc-a99d-4527-99af-ecf65124731b"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("ff494d37-c94c-487b-95bd-863a8bdaddb9"),
                            ResourceCode = "SystemMngmt.PermissionMngmt.RoleMngmt.Update",
                            ResourceName = "更改",
                            ResourceType = 2,
                            SortNO = 2
                        },
                        new
                        {
                            ID = new Guid("e4c2a130-cc9a-42df-a56f-ba173e05898d"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("84448bbd-1ada-458d-8c9f-799c07331e51"),
                            ResourceCode = "SystemMngmt.PermissionMngmt.ScopeMngmt",
                            ResourceName = "范围管理",
                            ResourceType = 1,
                            SortNO = 2
                        },
                        new
                        {
                            ID = new Guid("e66cf7c5-7679-4b30-8655-2b056f7b8513"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("84448bbd-1ada-458d-8c9f-799c07331e51"),
                            ResourceCode = "SystemMngmt.PermissionMngmt.AssignmnentMngmt",
                            ResourceName = "授权管理",
                            ResourceType = 1,
                            SortNO = 3
                        },
                        new
                        {
                            ID = new Guid("8f2a9f1d-dc12-45f2-8e0e-865e09d81968"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("897335d5-562b-4e86-85e0-8aff46d01f7a"),
                            ResourceCode = "SystemMngmt.JobMngmt",
                            ResourceName = "任务管理",
                            ResourceType = 1,
                            SortNO = 2
                        },
                        new
                        {
                            ID = new Guid("aabe04af-602c-4dd4-9274-50a173ec6042"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("897335d5-562b-4e86-85e0-8aff46d01f7a"),
                            ResourceCode = "SystemMngmt.MessageMngmt",
                            ResourceName = "消息管理",
                            ResourceType = 1,
                            SortNO = 3
                        },
                        new
                        {
                            ID = new Guid("539d1f4b-5555-4765-95d2-da9d4a5e67d1"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("897335d5-562b-4e86-85e0-8aff46d01f7a"),
                            ResourceCode = "SystemMngmt.LogMngmt",
                            ResourceName = "日志管理",
                            ResourceType = 1,
                            SortNO = 4
                        },
                        new
                        {
                            ID = new Guid("e4a756b3-34e9-45ef-b6e6-d831e05a7c82"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("88888888-8888-8888-8888-888888888888"),
                            ResourceCode = "PlatformMngmt",
                            ResourceName = "平台管理",
                            ResourceType = 1,
                            SortNO = 5
                        },
                        new
                        {
                            ID = new Guid("f29fc97f-79fc-4fc4-971f-fa41425acb6f"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("e4a756b3-34e9-45ef-b6e6-d831e05a7c82"),
                            ResourceCode = "PlatformMngmt.ResourceMngmt",
                            ResourceName = "资源管理",
                            ResourceType = 1,
                            SortNO = 1
                        },
                        new
                        {
                            ID = new Guid("ef83e251-ecec-4835-8acc-afd7284b2e2a"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ParentResourceID = new Guid("e4a756b3-34e9-45ef-b6e6-d831e05a7c82"),
                            ResourceCode = "PlatformMngmt.TenantMngmt",
                            ResourceName = "租户管理",
                            ResourceType = 1,
                            SortNO = 2
                        });
                });

            modelBuilder.Entity("SystemService.Domain.Tenant", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateIn");

                    b.Property<string>("CreatedBy");

                    b.Property<int>("SortNO");

                    b.Property<string>("TenantCode")
                        .IsRequired();

                    b.Property<string>("TenantDesc");

                    b.Property<string>("TenantLogo")
                        .IsRequired();

                    b.Property<string>("TenantName")
                        .IsRequired();

                    b.Property<string>("TenantUrl")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("UpdateIn");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("ID");

                    b.HasIndex("TenantCode")
                        .IsUnique();

                    b.ToTable("Tenant");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a6b87678-0c6d-4ba6-a13b-386e32460100"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortNO = 0,
                            TenantCode = "SYSTEM",
                            TenantLogo = "",
                            TenantName = "SYSTEM",
                            TenantUrl = "www.system.com"
                        },
                        new
                        {
                            ID = new Guid("fd602bb6-9bef-4ece-86f0-0ec49d046291"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortNO = 1,
                            TenantCode = "MSFT",
                            TenantLogo = "",
                            TenantName = "Microsoft",
                            TenantUrl = "www.microsoft.com"
                        },
                        new
                        {
                            ID = new Guid("839320d0-2db1-436f-ab21-6bf15d5e47cb"),
                            CreateIn = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SortNO = 2,
                            TenantCode = "GOOG",
                            TenantLogo = "",
                            TenantName = "Google",
                            TenantUrl = "www.Google.com"
                        });
                });

            modelBuilder.Entity("SystemService.Domain.Resource", b =>
                {
                    b.HasOne("SystemService.Domain.Resource", "ParentResource")
                        .WithMany("ChildrenResources")
                        .HasForeignKey("ParentResourceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
